### ISSUE TITLE
Issue with oxygen saturation.

### ISSUE THREAD

**Issue by Pbhaskarreddy** [YahyaOdeh/HealthWatcher#1]
Even though, I put finger for the oxygen saturation testing, it is showing measurement failed. I am using Lollipop version. Please check the same at your end. What is the issue.

**Comment by YahyaOdeh** [comment]
Have you tried doing the all vital signs test ? 

have you tried all tests separately ?

Because for me it is working fine .. as I said it need lots of customization duo to mobile/camera differences.
