### ISSUE TITLE
Could you add your app into f-droid?

### ISSUE THREAD

**Issue by KOLANICH** [YahyaOdeh/HealthWatcher#2]

**Comment by IzzySoft** [comment]
Oh, he wasn't quite that verbous… F-Droid maintainer here. OP [opened a request](https://gitlab.com/fdroid/rfp/-/issues/1146) with us to have your app included with the [F-Droid](https://f-droid.org/) catalog. Would you support that? If yes, it would be great if you could establish [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo (for description, screenshots etc. – binaries are not needed by us), and [tag your releases](https://github.com/YahyaOdeh/HealthWatcher/releases)?

**Comment by IzzySoft** [comment]
@YahyaOdeh any chance for an answer? That Request at F-Droid is still open, waiting for this issue here to be solved…

**Comment by KOLANICH** [comment]
@AbdullahFaqeir, @ac121102

**Comment by IzzySoft** [comment]
Oh, another verbose one :disappointed: Guess that means "No" then. :man_shrugging:
