### ISSUE TITLE
Source Code App Crash

### ISSUE THREAD

**Issue by linkstudy** [YahyaOdeh/HealthWatcher#4]
is there anyone? who can solve the error of this application. Because this application crashed when click on any button, both emulator and mobile..

**Comment by YahyaOdeh** [comment]
give camera permission for the application

**Comment by Rendelnalangan** [comment]
what kind of IDE you started to develop this app?

**Comment by YahyaOdeh** [comment]
Android studio

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Rendelnalangan** [comment]
you'r so very impressive..
