### ISSUE TITLE
measurement field in check all

### ISSUE THREAD

**Issue by abdallaemadeldin** [YahyaOdeh/HealthWatcher#8]
it takes too long to get the data when i check all how can i solve this?
and in some devices it's never return values.
can you help me
@YahyaOdeh @AbdullahFaqeir

**Comment by AbdullahFaqeir** [comment]
Hello,

Can you please provide a log data and details about the device you’re using.

Thanks.

**Comment by ombinar** [comment]
Hi there,

Could we have a Flutter plugin for this?

Thanks,

Ricky

**Comment by AbdullahFaqeir** [comment]
Hello @ombinar 

As this project isn’t actually a library so it needs to be completely exported into a flutter app.

What we’ll try to do is to export the whole functionality into a gradle library so it can properly exported as a flutter module.

We’ll make sure to update you guys once we do it.

Thanks.

**Comment by YahyaOdeh** [comment]
Hello, As of my testing and what I've wrote in description that it needs more optimization to work with more devices. Main problem if you want the application to work with mobiles containing 2 or more lenses probably will be to upgrade the camera api from version 1 to 2, probably that will solve the problem with modern android devices that contains multiple lenses.

And about the data fetching if you see it is slow, because the application works as if you record the video then call the frames back and eventually do the math to give the vital sings results, you can check the code comments for better understanding too.

**Comment by abdallaemadeldin** [comment]
@AbdullahFaqeir i use note4 for testing

**Comment by abdallaemadeldin** [comment]
@YahyaOdeh can you please tell me how to upgrade the camera api i'm a reactnative developer and i just know how to implement native packages with my code but idk how to develop native apps using java i have a small exp in this section. thanks

**Comment by YahyaOdeh** [comment]
@abdallaemadeldin As a start you have to go back to the used functions of fetching the data from the camera and understand them at camera api V1, compare the image processing that is done and if the same math/calculation works at camera api V2 works after also using the fitted functions same as the previous version.

In other words you'll have to understand the difference between the functions used between camera api v 1 and v 2 then know the difference at the fetched frames data and how to implement an image processing functions that suits camera Api 2 to get the color intensities you require to get vital signs data.

You can start by understanding the image processing at the code / camera api 1 then finally at camera api 2 then you might be able to implement the application to work with camera api 2.

also you can start by reading the following links:

https://developer.android.com/reference/android/hardware/Camera
https://developer.android.com/reference/android/hardware/camera2/package-summary

Hope I helped, Good luck :)

**Comment by abdallaemadeldin** [comment]
@YahyaOdeh thanks for your time and your help i appreciate this man.

**Comment by ombinar** [comment]
I'm new to Flutter plugins. Will the export works only for Android or iOS
too?

Thanks,

Ricky Ombina

**Comment by ombinar** [comment]
Hi Abdullah,

Please let me know when you're able to export the code for Flutter.

Thanks,

Ricky Ombina

**Comment by abdallaemadeldin** [comment]
@ombinar hello ricky i'm a react native developer and idk how can i export this code for flutter

**Comment by abdallaemadeldin** [comment]
@YahyaOdeh hey bro can u give me any social media for you?
