### ISSUE TITLE
Heart rate measurment not accuret

### ISSUE THREAD

**Issue by abdallaemadeldin** [YahyaOdeh/HealthWatcher#9]
@YahyaOdeh @AbdullahFaqeir hey bro i have test the heart rate measurement and every single time i got a value with a big diff with the last one can you help me?

**Comment by YahyaOdeh** [comment]
Hello, hope you're doing fine. For me that doesn't happen and works fine but as I said at the read.me that the code in general needs more optimization to work correctly on more devices. my device that I did the testing on was Sony Z2 and honestly I didn't have the time or the resources to test on a wide range or devices so yeah probably it won't be accurate on all devices and needs optimization as a code to work with a wider range of them.

**Comment by abdallaemadeldin** [comment]
@YahyaOdeh  can i have ur contact info or any social media?

**Comment by YahyaOdeh** [comment]
You can contact me at my email, I respond as soon as I see the email.

Yahya_odeh@outlook.com

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
